from beanie import Document
from pydantic import Field
from typing import Optional
from datetime import datetime, timezone


class User(Document):
    """
    Created once when the extension is installed.
    user_id = UUID generated by chrome.storage on first install.
    name = entered by user on first run (e.g. "Arjun").
    """
    user_id: str                          # UUID from chrome.storage
    name: str                             # display name
    email: Optional[str] = None           # Auth email
    hashed_password: Optional[str] = None # Auth password hash
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "users"                    # MongoDB collection name


class Session(Document):
    """
    One session = one continuous monitoring window.
    Extension sends this every ~30 seconds or on tab close.

    Raw signals (what content_script.js measures):
      - wpm            → typing speed in words per minute
      - error_rate     → typos per minute
      - scroll_rate    → pages scrolled per minute
      - click_delay    → average ms between click and next action
      - rage_clicks    → number of rapid repeated clicks

    Derived:
      - fatigue_score  → calculated in content_script.js (0–100)
      - site_url       → current tab URL
      - duration_mins  → how long this session has been running
    """
    user_id: str
    fatigue_score: float                  # 0–100, higher = more fatigued
    wpm: float                            # words per minute
    error_rate: float                     # errors per minute
    scroll_rate: float                    # pages per minute
    click_delay: float                    # ms average
    rage_clicks: int                      # count
    site_url: str                         # e.g. "reddit.com"
    duration_mins: float                  # session length so far
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "sessions"


class Suggestion(Document):
    """
    AI suggestion generated by Ollama (Mistral) when fatigue_score
    crosses 50 (Fragile) or 70 (Strained).
    Stored so the dashboard can show suggestion history.
    """
    user_id: str
    session_id: str                       # links back to the Session document
    threshold: int                        # 50 or 70 — which threshold triggered this
    status: str                           # "fragile" or "strained"
    suggestion_text: str                  # Claude's full response
    site_url: str                         # page user was on when triggered
    fatigue_score: float                  # score at time of trigger
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "suggestions"


class UserSettings(Document):
    """
    User preferences saved from the Settings page of the dashboard.
    One document per user — upserted (created or updated) on save.
    """
    user_id: str

    # Signal weights (from sliders in settings page)
    typing_weight: int = 40              # % weight for typing signal
    scroll_weight: int = 30             # % weight for scroll signal

    # Thresholds (default 50 + 70, user can adjust)
    fragile_threshold: int = 50
    strained_threshold: int = 70

    # Feature toggles (from toggle switches in settings page)
    focus_mode_enabled: bool = True
    break_reminders: bool = True
    strained_alerts: bool = True
    ui_simplification: bool = True
    store_history: bool = True
    high_contrast: bool = False
    larger_targets: bool = False

    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "user_settings"


class OllamaChat(Document):
    """
    Persists every AI interaction (chat, summarise, classify) that
    flows through the /api/ollama/chat endpoint.

    Allows the dashboard to display a history of AI conversations
    and makes it easy to add analytics later.
    """
    user_id: str                          # from x-user-id header
    mode: str                             # "chat" | "summarise" | "classify"
    page_title: str = ""                  # page context (may be empty)
    user_message: str                     # what the user asked (truncated)
    reply: str                            # Mistral's response
    model: str = "mistral"                # model name used
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    class Settings:
        name = "ollama_chats"             # MongoDB collection name

class TaskAnchor(Document):
    """
    Records an anchored task session.
    """
    user_id: str
    task_name: str
    status: str = "active"                # "active", "paused", "completed"
    start_time: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    end_time: Optional[datetime] = None

    class Settings:
        name = "task_anchors"

class TaskDriftEvent(Document):
    """
    Logs when a user drifts from their anchored task.
    """
    user_id: str
    task_anchor_id: str                   # links to TaskAnchor
    task_name: str
    site_url: str                         # where they drifted to
    page_title: str
    action_taken: str                     # "back_to_task", "its_research", "ignored"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "task_drift_events"

class BlocklistRule(Document):
    """
    Stores a domain to block and the blocking mode.
    """
    user_id: str
    domain: str                           # e.g. "reddit.com"
    mode: str                             # "hard", "soft", "fatigue", "time", "session"
    threshold: Optional[float] = None     # used if mode == "fatigue" (e.g. 65)
    avg_score_increase: Optional[float] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "blocklist_rules"

class MemoryNote(Document):
    """
    Working Memory Aid notes.
    """
    user_id: str
    content: str
    note_type: str                        # "thought", "bookmark", "redirect", "fragment"
    url: Optional[str] = None
    domain: Optional[str] = None
    task_anchor_id: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "memory_notes"